package br.edu.mg.unifal.factory;

import br.edu.mg.unifal.domain.Address;
import br.edu.mg.unifal.domain.User;
import br.edu.mg.unifal.enumerator.Gender;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public class UserAssembler {

    public static List<User> assemble() {
        return Arrays.asList(
                User.builder()
                        .firstName("Elias")
                        .lastName("Haley")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(1992, 3, 22, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Stevie Estate")
                                .number("86525")
                                .complement("Apt. 965")
                                .zipCode("89407-2644")
                                .city("West Conrad")
                                .state("Kansas")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Helen")
                        .lastName("Connolly")
                        .gender(Gender.FEMALE)
                        .birthdate(LocalDateTime.of(1990, 8, 21, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Stevie Estate")
                                .number("86525")
                                .complement("Apt. 965")
                                .zipCode("89407-2644")
                                .city("West Conrad")
                                .state("Kansas")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Noel")
                        .lastName("Washington")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(1998, 2, 2, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Mayer Knolls")
                                .number("641")
                                .complement("Suite 332")
                                .zipCode("62515")
                                .city("Consuelofurt")
                                .state("Wyoming")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Elliot")
                        .lastName("Powell")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(1998, 9, 21, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Padberg Mall")
                                .number("175")
                                .complement("Suite 529")
                                .zipCode("08198-5433")
                                .city("East Tylerchester")
                                .state("Vermont")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Tiffany")
                        .lastName("House")
                        .gender(Gender.FEMALE)
                        .birthdate(LocalDateTime.of(1998, 9, 21, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Padberg Mall")
                                .number("175")
                                .complement("Suite 529")
                                .zipCode("08198-5433")
                                .city("East Tylerchester")
                                .state("Vermont")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Eric")
                        .lastName("Fleming")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(2000, 10, 15, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Mueller Circle")
                                .number("941")
                                .complement("Suite 912")
                                .zipCode("56999-7708")
                                .city("Skylafort")
                                .state("Wyoming")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Lori")
                        .lastName("Romero")
                        .gender(Gender.FEMALE)
                        .birthdate(LocalDateTime.of(1999, 6, 8, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Mueller Circle")
                                .number("941")
                                .complement("Suite 912")
                                .zipCode("56999-7708")
                                .city("Skylafort")
                                .state("Wyoming")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Jake")
                        .lastName("Vasquez")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(1990, 05, 18, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Kristopher Shores")
                                .number("9579")
                                .complement("")
                                .zipCode("43982-8992")
                                .city("New Dejuanhaven")
                                .state("Washington")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Mercedes")
                        .lastName("Burgess")
                        .gender(Gender.PREFER_NOT_SAY)
                        .birthdate(LocalDateTime.of(1990, 11, 28, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Kristopher Shores")
                                .number("9579")
                                .complement("")
                                .zipCode("43982-8992")
                                .city("New Dejuanhaven")
                                .state("Washington")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Josef")
                        .lastName("Oconnor")
                        .gender(Gender.MALE)
                        .birthdate(LocalDateTime.of(1990, 02, 20, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Yvonne Divide")
                                .number("411")
                                .complement("Suite 766")
                                .zipCode("29846")
                                .city("Millerstad")
                                .state("Virginia")
                                .country("USA")
                                .build())
                        .build(),
                User.builder()
                        .firstName("Theresa")
                        .lastName("Knight")
                        .gender(Gender.FEMALE)
                        .birthdate(LocalDateTime.of(1992, 12, 14, 0, 0, 0))
                        .address(Address.builder()
                                .streetName("Yvonne Divide")
                                .number("411")
                                .complement("Suite 766")
                                .zipCode("29846")
                                .city("Millerstad")
                                .state("Virginia")
                                .country("USA")
                                .build())
                        .build()
        );
    }

}
